version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "3000:80" # Expose NGINX's default port to 3000 on the host
    networks:
      - mynetwork
    volumes:
      - ./local.conf:/etc/nginx/conf.d/default.conf

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # UNCOMMENT FOR MANUAL API TESTING
    ports:
      - "3001:3001" # Backend port, if needed. Adjust as per your application configuration.
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      # Add other environment variables or use env_file if needed
    env_file:
      - .env
    networks:
      - mynetwork

  db:
    image: mysql  # Using official MySQL image
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  dbdata:
